# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: llama-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: llama
  template:
    metadata:
      labels:
        app: llama
    spec:
      containers:
      - name: llama-container
        image: <your-dockerhub-username>/llama:latest
        ports:
        - containerPort: 8501